### ISSUE TITLE
Odpočet busy času

### ISSUE THREAD

**Issue by Arci224** [LeoSight/quarters#14]
Napadlo mě ten busy time řešit pomocí JavaScriptu a odpočtu za pomoci něj, než natvrdo refreshovat stránku co 2 minuty? https://github.com/LeoSight/quarters/blob/6ef7774f81dd287d28f341d86c75ceec3105de8b/templates/game/map.twig#L3-L5 A zároveň by se to dalo využít i kdyby busy time byl potom jiný než 2 minuty. Jelikož by to mohlo brát pomocí Timestampu.
Co si o tom myslíte?

**Comment by jnovakdev** [comment]
Taky mě to napadlo. BE předá do kdy bude busy, JS spočítá kolik do toho momentu zbývá času. No jo, ale... nic se nezmění, ty stejně budeš muset tu stránku refreshnout, abys mohl vybrat kam dál. Takže auto-refresh zůstane tak či onak, akorát můžeme zpříjemnit to předávání informace za jak dlouho k němu dojde.
